### ISSUE TITLE
What time could the mongo-connector support the MongoDB v3.6

### ISSUE THREAD

**Issue by mydaypower1** [yougov/mongo-connector#819]
You know the MongoDB's latest and stable version is v3.6 now, We are planning to upgrade to v3.6,
But when we come back here in mongo-connector in Github, It do not say can support v3.6 of MongoDB.
<<Getting Started: mongo-connector supports Python 2.6, 2.7, and 3.3+ and MongoDB versions 2.4, 2.6, 3.0, 3.2, and 3.4.>>

**Could you please let us know what time could the mongo-connector support the MongoDB v3.6 if possible??**

Thank you so much

**Comment by jaraco** [comment]
See #781. The next release should include support for MongoDB 3.6.

**Comment by jaraco** [comment]
Hmm. There are indications that some tests [fail on MongoDB 3.6](https://travis-ci.org/yougov/mongo-connector/jobs/440669776) or maybe on Python 3.6.

Despite the hard blocker fixed by the 2.6 release, more work remains to ensure proper MongoDB 3.6 support:

- [ ] Get tests passing against MongoDB 3.6.
