### ISSUE TITLE
Nested Documents

### ISSUE THREAD

**Issue by Crossener** [yougov/mongo-connector#89]
How to use mongo connector to indexing fields of embedded documents for solr? For example the field StreetName of:

```
{
  "_id" : ObjectId("52fa3674395d4602b8be4a1b"),
  "AddressDirectory" : {
    "Owner" : "Mayank",
    "Age" : "24",
    "Company" : "BIPL",
    "Address" : {
      "HouseNo" : "4",
      "StreetName" : "Rohini",
      "City" : "Delhi"
    }
  }
} 
```

The [manual](https://github.com/SelfishInc/solr-mongo-connector) says the connector flattens the nested documents but in solr I cant see the flatted field StreetName.

**Comment by annvakulchyk** [comment]
Hi, is it possible to keep existing structure in MongoDB for Solr? Solr supports multivalues so I have an array in Mongo and expect Solr to insert array as well, copyField solution is not an option for me because I have a lot of dynamic fields and I can't define all fields in my schema.xml. So it's really critical to have ability to insert arrays like:
<code> "category_ids" : [ 
        NumberLong(2), 
        NumberLong(13), 
        NumberLong(14), 
        NumberLong(15), 
        NumberLong(16), 
        NumberLong(37)
    ]</code>

**Comment by llvtt** [comment]
Hi Anna,

Mongo Connector automatically unwinds arrays. For the rationale behind 
this, see 
https://github.com/10gen-labs/mongo-connector/issues/148#issuecomment-48931974. 
This is not configurable right now.
